### ISSUE TITLE
Chrome Web Store - Rejection Notification

### ISSUE THREAD

**Issue by ganobrega** [ganobrega/vtexp#6]
Well, the chrome web store is rejecting the publishing of VTEXP.

These are the justifications:
- The items should work and provide some ease after installation.
- Items must provide the promised functionality according to the item description.

**Comment by AmySteam** [comment]
Hi there, my name is Amy from [jackandamydev](https://www.youtube.com/channel/UCVj3dGw75v8aHFYD6CL1tFg/). And I have helped other chrome developers pass the chrome web store review process.

My best advice for this message is to include in the [detailed description](https://youtu.be/JZTO-Z8MBEc?t=217) instructions of how to get started (for example by clicking on the popup to use the extension, etc). And then make a video showing how the description matches how the extension works.

This is the best way to show the Chrome Web Store team how the extension is actually working.

If you receive any other rejection notice, please let me know, maybe I can help. But by quickly looking at your permissions, you only need to request activeTab (not both tabs and activetab), because you are using chrome.tabs.query in the popup page.

Good luck with your extension,
All the best,
Amy
[@jackandamydev](https://twitter.com/JackandAmyDev)

**Comment by ganobrega** [comment]
Hi Amy!

I was in doubt if both tab permissions were needed.

Thank you very much for the advices!

**Comment by ganobrega** [comment]
I did the recommendations but still getting the rejection notification. 😕
I will try again again soon.

**Comment by ganobrega** [comment]
The extension passed the publication !!
I'm very happy now!!
Thanks a lot for the help!!

https://chrome.google.com/webstore/detail/vtexp/eoekghnklnjjeefkfmjkccpdngejmaeo?hl=pt-BR
